# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180116_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2, verbose_name='Your gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=999999999, max_length=10, verbose_name='Phone number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
