# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-11 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('gen', 'General'), ('cse', 'CSE'), ('ec', 'ECE'), ('eee', 'EEE'), ('it', 'IT'), ('me', 'ME')], default='gen', max_length=3),
        ),
        migrations.AddField(
            model_name='event',
            name='coordinators',
            field=models.TextField(default='me', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='fee',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='imageurl',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_url', to='events.Event'),
        ),
    ]
