# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-25 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180224_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='imageurl',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('wor', 'Workshops'), ('com', 'Competitions'), ('sho', 'Shows')], default='wor', max_length=3),
        ),
    ]
