# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-25 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180225_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('gen', 'General'), ('cse', 'CSE'), ('ece', 'ECE'), ('eee', 'EEE'), ('it', 'IT'), ('me', 'ME')], default='gen', max_length=3),
        ),
    ]
