# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-25 06:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180225_0626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='type',
            new_name='_type',
        ),
    ]
