# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-25 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20180225_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='townscript_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
