# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-26 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20180226_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='coordinators',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
