# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_posterurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='prize',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='_type',
            field=models.CharField(choices=[('wor', 'Workshops'), ('com', 'Competitions'), ('sho', 'Shows'), ('oth', 'Other')], default='wor', max_length=3, verbose_name='Type'),
        ),
    ]
