# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-01 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20180227_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageurl',
            name='event',
        ),
        migrations.DeleteModel(
            name='ImageUrl',
        ),
    ]
