# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-05 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20180301_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pdfurl',
            field=models.URLField(blank=True),
        ),
    ]
